comparing double with int64 requires a cast
frida/quickjs pull request #6
Opened 2023-01-01 23:50 UTC by trufae

2023-01-26 16:30 UTC, oleavr requested changes
Thanks!

2023-01-26 16:30 UTC, oleavr commented on quickjs.h
> +           val = INT32_MIN;
Indentation should be 4 spaces (here and below).

2023-01-27 17:07 UTC, trufae commented on quickjs.h
> +           val = INT32_MIN;
fixed

2023-01-27 17:07 UTC, trufae commented
also, rebased. feel free to squash or change the commit message

2023-04-26 20:16 UTC, merged